# WARNING: This Docker Compose file is for development purpose only. Never use
# it on production
version: "3.3"
services:
  postgres:
    build: ./postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - ../pgdata-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: "${POSTGRES_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DATABASE:-postgres}"
      # Enable SSL with self-signed certificate generated on the fly
      POSTGRES_SSL: "${POSTGRES_SSL:-1}"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    pgadmin:
